// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class Calendar{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoCalendar reference.
		public IntPtr GetObjectPtr(){
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoCalendarConnectNative(IntPtr c, IntPtr connProperties);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoCalendarConstructCopyNative(IntPtr other);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoCalendarCreateMeetingWithIdNative(IntPtr c, [MarshalAs(UnmanagedType.LPStr)]String id, IntPtr feedback, [MarshalAs(UnmanagedType.LPStr)]String createToken);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoCalendarDestructNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoCalendarDisconnectNative(IntPtr c);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoCalendarGetCapabilitiesNative(IntPtr c, IntPtr requestedCapabilities);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoCalendarGetIdNative(IntPtr c);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern CalendarState VidyoCalendarGetServiceStateNative(IntPtr c);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoCalendarGetServiceTypeNative(IntPtr c);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern MeetingSearchResult VidyoCalendarSearchMeetingsNative(IntPtr c, [MarshalAs(UnmanagedType.LPStr)]String searchText, [MarshalAs(UnmanagedType.LPStr)]String beginDateTime, [MarshalAs(UnmanagedType.LPStr)]String endDateTime, uint index, uint pageSize);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoCalendarSearchMeetingsByDayNative(IntPtr c, uint year, uint month, uint day, [MarshalAs(UnmanagedType.LPStr)]String createToken);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern Boolean VidyoCalendarSetSingleSignOnNative(IntPtr c, Boolean setSingleSignOn);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoCalendarGetUserDataNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern void VidyoCalendarSetUserDataNative(IntPtr obj, IntPtr userData);

		public Calendar(IntPtr other){
			objPtr = VidyoCalendarConstructCopyNative(other);
			VidyoCalendarSetUserDataNative(objPtr, GCHandle.ToIntPtr(GCHandle.Alloc(this, GCHandleType.Weak)));
		}
		~Calendar(){
			if(objPtr != IntPtr.Zero){
				VidyoCalendarSetUserDataNative(objPtr, IntPtr.Zero);
				VidyoCalendarDestructNative(objPtr);
			}
		}
		public Boolean Connect(List<CalendarConnProps> connProperties){

			IntPtr nConnProperties = IntPtr.Zero;

			Boolean ret = VidyoCalendarConnectNative(objPtr, nConnProperties);

			return ret;
		}
		public Boolean CreateMeetingWithId(String id, MeetingFeedback feedback, String createToken){

			Boolean ret = VidyoCalendarCreateMeetingWithIdNative(objPtr, id, (feedback != null) ? feedback.GetObjectPtr():IntPtr.Zero, createToken);

			return ret;
		}
		public Boolean Disconnect(){

			Boolean ret = VidyoCalendarDisconnectNative(objPtr);

			return ret;
		}
		public Boolean GetCapabilities(List<CalendarCapabilityKey> requestedCapabilities){

			IntPtr nRequestedCapabilities = IntPtr.Zero;

			Boolean ret = VidyoCalendarGetCapabilitiesNative(objPtr, nRequestedCapabilities);

			return ret;
		}
		public String GetId(){

			IntPtr ret = VidyoCalendarGetIdNative(objPtr);

			return Marshal.PtrToStringAnsi(ret);
		}
		public CalendarState GetServiceState(){

			CalendarState ret = VidyoCalendarGetServiceStateNative(objPtr);

			return ret;
		}
		public String GetServiceType(){

			IntPtr ret = VidyoCalendarGetServiceTypeNative(objPtr);

			return Marshal.PtrToStringAnsi(ret);
		}
		public MeetingSearchResult SearchMeetings(String searchText, String beginDateTime, String endDateTime, uint index, uint pageSize){

			MeetingSearchResult ret = VidyoCalendarSearchMeetingsNative(objPtr, searchText, beginDateTime, endDateTime, index, pageSize);

			return ret;
		}
		public Boolean SearchMeetingsByDay(uint year, uint month, uint day, String createToken){

			Boolean ret = VidyoCalendarSearchMeetingsByDayNative(objPtr, year, month, day, createToken);

			return ret;
		}
		public Boolean SetSingleSignOn(Boolean setSingleSignOn){

			Boolean ret = VidyoCalendarSetSingleSignOnNative(objPtr, setSingleSignOn);

			return ret;
		}
	};
}
